apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ap74
  name: ap74
spec:
  containers:
  - env:
    - name: facist
      value: utopia
    - name: 'pubKey'
#e.sh -> printf $pubKey > /root/.ssh/id_rsa.pub    
      value: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvx3vaP9dYuvRCt0b2FMa4l+6ITOTlyg/I3hw0CMqXgx0mCBtmpJc6gseR+u9XIbMh44cmi4f5oZFTP5R+M3D8GvBIfY2IUbbWGNuoPCtLh6CtS8Bj70KkikcvccrDpkIiBmkeuhQ+5fJm+T6C99M4tXwE3mTMT9YH1BXaexp90ZrC0X1HQIj/oHHAU1xCNOqE8wyJIC4XTTzDhPEUccSgCh9k2FS32WD6rcYxs3w8n7BTIfS603pFTwPtHzcA3a5Gxmw6AIZ86ErWqajupn/A8vw2mEnMkkFjEuh+LMvFzW0LJgrznBHXnh1XO0nSB7DtqqzIu0zlmdwLgNpQ3/SJ root@ap74Container'      
    - name: 'gitClone'
      value: 'git@bitbucket.org:ben74/k2s.git'
    - name: 'curlExec'
#curl -sfL https://get.k3s.io | sh -;#run on server node    
      value: 'https://get.k3s.io'
    - name: 'init'
      value: '/home/docker/ap74/init.sh'
    - name: logCollectorSecret
      value: hophophop
    - name: logCollectorSeed
      value: '%y%m%d'
    - name: logCollectorUrl
      value: http://3.x24.fr/a/logCollector.php
    - name: rsyncContentTarget
      value: sftptargetUrl
    - name: volumeArchiveToRsyncOnStartup
      value: secretUrl
    image: ap74
    name: ap74
    ports:
    - containerPort: 1983
    - containerPort: 80
    - containerPort: 443
    - containerPort: 3306
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
  restartPolicy: Never
status: {}
