version: "3"
services:
  ap74:
  #expose: map to windows ip ( dmz )
    ports:
      - "1983:1983"
      - "80:80"
      - "443:443"
      - "3306:3306"
    networks:
      - default      
    restart: 'no'
    build:
        context: docker/ap74/
        dockerfile: Apache74FPM.dockerfile
    container_name: ap74
    image: ap74    
    volumes:
#https://stackoverflow.com/questions/52037957/kubernetes-share-a-directory-from-your-local-system-to-kubernetes-container    
    - apacheMySql1:/z/
    #web document root : delegated : faster writes, cached : faster read    s
    - ./:/home/:cached

  phpgit_php74:
    restart: 'no'
    build:
        context: docker/
        dockerfile: 74FPM.dockerfile
    container_name: phpgit_php74
    image: phpgit_php74
    expose:
     - "9074"
    networks:
     - default
    volumes:
        - ./:/home/:cached
#     - apacheMysql:/z/
#- ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG="serverName=php.home"
      - XDEBUG_CONFIG="remote_host=192.168.1.99"
      
  phpgit_php8:
    restart: 'no'
    build:
        context: docker/php8/
        dockerfile: php8fpm.dockerfile
    container_name: phpgit_php8
    image: phpgit_php8
#exposed
    ports:
      - 21:21
      - 22:22
      - 80:80
      - 443:443
      - 8080:8080
#between containers      
    expose:
     - 9080
    networks:
     - default
    volumes:
     - ./:/home/:cached
    environment:
      - PHP_IDE_CONFIG="serverName=php.home"
      - XDEBUG_CONFIG="remote_host=192.168.1.99"

  selenium:
    restart: 'no'
    container_name: selenium
    #/dev/shm shall be writable ( user shares are not )
    #latest: antimony : 3.141.59
    #image: selenium/standalone-chrome
    image: selenium/standalone-chrome:3.9.0-antimony
    #mem_limit: 3400000000
    environment:
      - GRID_MAX_SESSION=1
      - GRID_TIMEOUT=60
      - GRID_BROWSER_TIMEOUT=60
    extra_hosts:
      #or ln -s /etc/hosts
      #since we cant pass any basic http auth with selenium ... just add the problematic hosts here
      - "mage2.local:192.168.99.100"
    expose:
      - "4444"
      - "5900"
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - default
    #shm_size: 2g
    volumes:
      #also known as sharing the global shm with a localhost volume, thats dirty, right, but avoids potentials OOM crashes, whut ?
      - tmpShm:/tmp
      - tmpShm:/dev/shm
      #- .:/z
    #entrypoint: /bin/bash /z/e.sh
#      - ~/home:/z
networks:
  default:
    external:
      name: "1"
volumes:
  tmpShm:
  apacheMySql1: